# Generated by Django 5.2.6 on 2025-10-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='amount_involved',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='branch_address_of_organisation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='description_of_tip',
            field=models.TextField(default='description of tip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='misconduct_status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='yes', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='organisation_name',
            field=models.CharField(default='FMFBN', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='organisation_type',
            field=models.CharField(choices=[('ministry', 'Ministry'), ('department', 'Department'), ('agency', 'Agency'), ('other', 'Other')], default='Ministry', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='other_agency_name',
            field=models.CharField(default='EFCC', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='other_agency_submitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='tip_type',
            field=models.CharField(choices=[('diversion_of_revenues', 'Diversion of Revenues'), ('curruption', 'Curruption'), ('noncompliance_with_efficiency_guidelines', 'NonCompliance with Efficiency Unit Expenditure Guidelines/Circulars'), ('fraud', 'Fraud'), ('information_on_stolen_public_funds', 'Information on Stolen Public Funds'), ('manipulation_of_data_or_records', 'Manipulation of Data or Records'), ('conversion_of_funds_to_personal_use', 'Conversion of Funds to Personal Use'), ('violation_of_tsa_guidlines', 'Violation of TSA Guidlines'), ('misappropriation_of_public_funds', 'Misappropriation of Public Funds or Assets'), ('conflict_of_interest', 'Conflict of Interest'), ('collecting_soliciting_bribes', 'Collecting/Soliciting for Bribes'), ('fraudulent_payment', 'Fraudulent Payments'), ('undocumented_expenditures', 'Undocumented Expenditures'), ('splitting_contracts', 'Splitting of Contracts'), ('violation_Procurement_procedures', 'Violation of Procurement Procedures'), ('procurement_fraud', 'Procurement Fraud(Kickbacks, Over invoicing etc)'), ('nonremittance_lateremittance_revenue', 'NonRemittance/ Latre Remittance of Revenue'), ('concealed_funds_info', 'Information on Concealed Public Funds'), ('unapproved_expenditures', 'Unapproved Expenditures')], default='Curruption', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 2, 13, 3, 8, 388441, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='whistleblower_address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='whistleblower_email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='whistleblower_firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='whistleblower_mobile_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='whistleblower_surname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
