# Generated by Django 5.2.6 on 2025-10-02 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_amount_involved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='misconduct_status',
            new_name='misconduct_ongoing_status',
        ),
    ]
