# Generated by Django 5.2.6 on 2025-10-02 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_misconduct_status_report_misconduct_ongoing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='description',
        ),
    ]
