# Generated by Django 5.2.6 on 2025-10-02 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_report_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='transaction_date',
        ),
    ]
