# Generated by Django 5.2.6 on 2025-10-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='whistleblower_mobile_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
