# Generated by Django 5.2.6 on 2025-10-03 21:41

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_amount_involved_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='amount_involved',
            field=djmoney.models.fields.MoneyField(currency_choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], decimal_places=4, default_currency='NGN', max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='amount_involved_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], default='NGN', editable=False, max_length=3, null=True),
        ),
    ]
