# Generated by Django 5.2.6 on 2025-10-04 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_report_incident_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='incident_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='other_agency_submitted_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
