# Generated by Django 5.2.6 on 2025-10-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_report_incident_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
    ]
