# Generated by Django 5.2.6 on 2025-10-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_report_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='new_evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/'),
        ),
    ]
