# Generated by Django 5.2.6 on 2025-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_communication_new_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='new_evidence_file',
            field=models.FileField(blank=True, null=True, upload_to='new_evidence/'),
        ),
    ]
