# Generated by Django 5.2.6 on 2025-10-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_communication_new_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='tip_type',
            field=models.CharField(choices=[('diversion_of_revenues', 'Diversion of Revenues'), ('corruption', 'Corruption'), ('noncompliance_with_efficiency_guidelines', 'NonCompliance with Efficiency Unit Expenditure Guidelines/Circulars'), ('fraud', 'Fraud'), ('information_on_stolen_public_funds', 'Information on Stolen Public Funds'), ('manipulation_of_data_or_records', 'Manipulation of Data or Records'), ('conversion_of_funds_to_personal_use', 'Conversion of Funds to Personal Use'), ('violation_of_tsa_guidlines', 'Violation of TSA Guidlines'), ('misappropriation_of_public_funds', 'Misappropriation of Public Funds or Assets'), ('conflict_of_interest', 'Conflict of Interest'), ('collecting_soliciting_bribes', 'Collecting/Soliciting for Bribes'), ('fraudulent_payment', 'Fraudulent Payments'), ('undocumented_expenditures', 'Undocumented Expenditures'), ('splitting_contracts', 'Splitting of Contracts'), ('violation_Procurement_procedures', 'Violation of Procurement Procedures'), ('procurement_fraud', 'Procurement Fraud(Kickbacks, Over invoicing etc)'), ('nonremittance_lateremittance_revenue', 'NonRemittance/ Latre Remittance of Revenue'), ('concealed_funds_info', 'Information on Concealed Public Funds'), ('unapproved_expenditures', 'Unapproved Expenditures')], max_length=60),
        ),
    ]
