{{- if .Values.migration.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "whistleblower.fullname" . }}-migration-{{ randAlphaNum 5 | lower }}
  labels:
    {{- include "whistleblower.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    "helm.sh/hook": "post-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "whistleblower.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migration
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            - "sh"
            - "-c"
            - "python manage.py migrate --noinput && python manage.py collectstatic --noinput"
          envFrom:
            - configMapRef:
                name: {{ include "whistleblower.fullname" . }}-app-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "whistleblower.fullname" . }}-secrets
                  key: DJANGO_SECRET_KEY
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "whistleblower.fullname" . }}-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "whistleblower.fullname" . }}-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "whistleblower.fullname" . }}-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_URL
              value: "redis://:$(REDIS_PASSWORD)@{{ include "whistleblower.fullname" . }}-redis-svc:6379/1"
          {{- if .Values.storage.media.enabled }}
          volumeMounts:
            - name: media-storage
              mountPath: /code/media
          {{- end }}
      {{- if .Values.storage.media.enabled }}
      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: {{ include "whistleblower.fullname" . }}-media-pvc
      {{- end }}
{{- end }}
