apiVersion: v1
kind: Secret
metadata:
  name: {{ include "whistleblower.fullname" . }}-secrets
  labels:
    {{- include "whistleblower.labels" . | nindent 4 }}
type: Opaque
stringData:
  DJANGO_SECRET_KEY: {{ .Values.app.env.djangoSecretKey | quote }}
  DB_NAME: {{ .Values.database.dbName | quote }}
  DB_USER: {{ .Values.database.dbUser | quote }}
  DB_PASSWORD: {{ .Values.database.dbPassword | quote }}
  REPLICATION_USER: {{ .Values.database.replicationUser | quote }}
  REPLICATION_PASSWORD: {{ .Values.database.replicationPassword | quote }}
  REDIS_PASSWORD: {{ .Values.redis.password | quote }}
