name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    - run: docker build . --file Dockerfile --tag whistlebower:$(date +%s)
  
  uploadtoDocker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: upload image to docker
    - run: docker push kishimi8/kishimi8:whistlebower:$(date +%s)
